# Generated by Django 2.0.6 on 2018-06-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=9)),
                ('lugar_nacimiento', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('ocupacion_act', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('foto', models.IntegerField()),
            ],
        ),
    ]
