# Generated by Django 2.0 on 2018-07-07 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_inicio', models.IntegerField()),
                ('actividad', models.CharField(max_length=300)),
                ('riesgos', models.CharField(max_length=300)),
                ('epps', models.CharField(max_length=300)),
                ('tiempo', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentePatologicoFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentePatologicoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_patologia', models.CharField(max_length=100)),
                ('detalle_patologia', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AparatoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hallazgo', models.CharField(max_length=300)),
                ('detalle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AtencionEnfermeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2018, 7, 7, 23, 59, 4, 717779, tzinfo=utc))),
                ('motivo', models.CharField(max_length=300)),
                ('diagnostico', models.CharField(max_length=300)),
                ('plan_cuidados', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Chequeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2018, 7, 7, 23, 59, 4, 723251, tzinfo=utc))),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cifosis_acentuada', models.BooleanField()),
                ('contractura_muscular', models.BooleanField()),
                ('dolor', models.BooleanField()),
                ('lordosis_acentuada', models.BooleanField()),
                ('escoliosis', models.BooleanField()),
                ('motricidad', models.BooleanField()),
                ('lassegue', models.BooleanField()),
                ('detalle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2018, 7, 7, 23, 59, 4, 716353, tzinfo=utc))),
                ('motivo', models.CharField(max_length=300)),
                ('problema_actual', models.CharField(max_length=300)),
                ('revision', models.CharField(max_length=300)),
                ('prescripcion', models.CharField(max_length=300)),
                ('examen_fisico', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('consulta_medica', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.ConsultaMedica')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('factores_riesgo', models.CharField(max_length=300)),
                ('antecedente_laboral', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.AntecedenteLaboral')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.FloatField()),
                ('peso', models.FloatField()),
                ('indice_masa_corporal', models.FloatField()),
                ('columna', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.Columna')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenLaboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('archivo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Extremidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phalen', models.BooleanField()),
                ('tinel', models.BooleanField()),
                ('dolor', models.BooleanField()),
                ('signo_cajon_rodilla', models.BooleanField()),
                ('finkelstein', models.BooleanField()),
                ('motricidad', models.BooleanField()),
                ('observaciones', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('chequeo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.Chequeo')),
            ],
        ),
        migrations.CreateModel(
            name='Inmunizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=500)),
                ('fecha_aplicacion', models.DateField(default=datetime.datetime(2018, 7, 7, 23, 59, 4, 732437, tzinfo=utc))),
                ('ficha_medica', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.datetime(2018, 7, 7, 23, 59, 4, 719955, tzinfo=utc))),
                ('fecha_fin', models.DateField(default=datetime.datetime(2018, 7, 7, 23, 59, 4, 720033, tzinfo=utc))),
                ('dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piel_tegumentos', models.CharField(max_length=300)),
                ('cabeza_cuello', models.CharField(max_length=300)),
                ('torax', models.CharField(max_length=300)),
                ('corazon', models.CharField(max_length=300)),
                ('pulmones', models.CharField(max_length=300)),
                ('abdomen', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RegionLumbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolor_punio_percusion', models.BooleanField()),
                ('motricidad', models.BooleanField()),
                ('detalle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionAparatoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha_medica', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_sistolica', models.IntegerField()),
                ('presion_distolica', models.IntegerField()),
                ('pulso', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('atencion_enfermeria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.AtencionEnfermeria')),
                ('consulta_medica', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.ConsultaMedica')),
            ],
        ),
        migrations.CreateModel(
            name='SomaticoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apariencia', models.CharField(max_length=300)),
                ('estado_nutricional', models.CharField(max_length=300)),
                ('actividades_psicomotoras', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=5)),
                ('inmunizacion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.Inmunizacion')),
            ],
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='ocupacion_act',
            new_name='ocupacion_actual',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.Usuario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2018, 7, 7, 23, 59, 4, 714459, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 7, 23, 59, 4, 714602, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='permisomedico',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.Empleado'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.Empleado'),
        ),
        migrations.AddField(
            model_name='examenlaboratorio',
            name='ficha_medica',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='extremidades',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.Extremidades'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='ficha_medica',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='region_lumbar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.RegionLumbar'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='regional',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.Regional'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='signos_vitales',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.SignosVitales'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='somatico_general',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.SomaticoGeneral'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='enfermedad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.Enfermedad'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='permiso_medico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.PermisoMedico'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.Empleado'),
        ),
        migrations.AddField(
            model_name='atencionenfermeria',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.Empleado'),
        ),
        migrations.AddField(
            model_name='aparatosistema',
            name='revision_aparato_sistema',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.RevisionAparatoSistema'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicopersonal',
            name='consulta_medica',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.ConsultaMedica'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicopersonal',
            name='ficha_medica',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicofamiliar',
            name='consulta_medica',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.ConsultaMedica'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicofamiliar',
            name='enfermedad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.Enfermedad'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicofamiliar',
            name='ficha_medica',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AddField(
            model_name='antecedentelaboral',
            name='ficha_medica',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
    ]
