# Generated by Django 2.1rc1 on 2018-07-20 02:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_auto_20180707_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparatosistema',
            name='revision_aparato_sistema',
        ),
        migrations.RemoveField(
            model_name='diagnostico',
            name='permiso_medico',
        ),
        migrations.AddField(
            model_name='permisomedico',
            name='diagnostico',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Diagnostico'),
        ),
        migrations.AddField(
            model_name='revisionaparatosistema',
            name='aparato_sistema',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.AparatoSistema'),
        ),
        migrations.AlterField(
            model_name='antecedentelaboral',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='antecedentepatologicofamiliar',
            name='consulta_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.ConsultaMedica'),
        ),
        migrations.AlterField(
            model_name='antecedentepatologicofamiliar',
            name='enfermedad',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Enfermedad'),
        ),
        migrations.AlterField(
            model_name='antecedentepatologicofamiliar',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='antecedentepatologicopersonal',
            name='consulta_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.ConsultaMedica'),
        ),
        migrations.AlterField(
            model_name='antecedentepatologicopersonal',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='empleado',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Empleado'),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 20, 2, 56, 48, 709634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='motivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='plan_cuidados',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 20, 2, 56, 48, 709634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='columna',
            name='detalle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='empleado',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Empleado'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='examen_fisico',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 20, 2, 56, 48, 709634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='motivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='prescripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='problema_actual',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='revision',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='consulta_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.ConsultaMedica'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='enfermedad',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Enfermedad'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2018, 7, 20, 2, 56, 48, 709634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 20, 2, 56, 48, 709634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre_usuario',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Usuario'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='antecedente_laboral',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.AntecedenteLaboral'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='columna',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Columna'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='extremidades',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Extremidades'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='region_lumbar',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.RegionLumbar'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='regional',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Regional'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='signos_vitales',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.SignosVitales'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='somatico_general',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.SomaticoGeneral'),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='extremidades',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='chequeo',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Chequeo'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='empleado',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Empleado'),
        ),
        migrations.AlterField(
            model_name='inmunizacion',
            name='fecha_aplicacion',
            field=models.DateField(default=datetime.datetime(2018, 7, 20, 2, 56, 48, 725257, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inmunizacion',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='empleado',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Empleado'),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 7, 20, 2, 56, 48, 709634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 7, 20, 2, 56, 48, 709634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='regional',
            name='abdomen',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='regional',
            name='cabeza_cuello',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='regional',
            name='corazon',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='regional',
            name='piel_tegumentos',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='regional',
            name='pulmones',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='regional',
            name='torax',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='regionlumbar',
            name='detalle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='revisionaparatosistema',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='atencion_enfermeria',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.AtencionEnfermeria'),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='consulta_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.ConsultaMedica'),
        ),
        migrations.AlterField(
            model_name='somaticogeneral',
            name='actividades_psicomotoras',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='somaticogeneral',
            name='apariencia',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='somaticogeneral',
            name='estado_nutricional',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='inmunizacion',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Inmunizacion'),
        ),
    ]
