# Generated by Django 2.0.6 on 2018-07-08 02:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0004_auto_20180707_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparatosistema',
            name='revision_aparato_sistema',
        ),
        migrations.AddField(
            model_name='revisionaparatosistema',
            name='aparato_sistema',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historial.AparatoSistema'),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 8, 2, 50, 39, 184484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 8, 2, 50, 39, 193006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 8, 2, 50, 39, 182438, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2018, 7, 8, 2, 50, 39, 180433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 8, 2, 50, 39, 180433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inmunizacion',
            name='fecha_aplicacion',
            field=models.DateField(default=datetime.datetime(2018, 7, 8, 2, 50, 39, 207499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 7, 8, 2, 50, 39, 188493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 7, 8, 2, 50, 39, 188493, tzinfo=utc)),
        ),
    ]
