# Generated by Django 2.0.6 on 2018-07-12 02:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0011_auto_20180711_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentelaboral',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='antecedentepatologicofamiliar',
            name='consulta_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.ConsultaMedica'),
        ),
        migrations.AlterField(
            model_name='antecedentepatologicofamiliar',
            name='enfermedad',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Enfermedad'),
        ),
        migrations.AlterField(
            model_name='antecedentepatologicofamiliar',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='antecedentepatologicopersonal',
            name='consulta_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.ConsultaMedica'),
        ),
        migrations.AlterField(
            model_name='antecedentepatologicopersonal',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='empleado',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Empleado'),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 2, 11, 40, 88296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 2, 11, 40, 94316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='empleado',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Empleado'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='examen_fisico',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 2, 11, 40, 86295, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='motivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='prescripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='problema_actual',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='revision',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='consulta_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.ConsultaMedica'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='enfermedad',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Enfermedad'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='permiso_medico',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.PermisoMedico'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 2, 11, 40, 85292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 2, 11, 40, 85292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre_usuario',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Usuario'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='antecedente_laboral',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.AntecedenteLaboral'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='columna',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Columna'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='extremidades',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Extremidades'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='region_lumbar',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.RegionLumbar'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='regional',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Regional'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='signos_vitales',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.SignosVitales'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='somatico_general',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.SomaticoGeneral'),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='chequeo',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Chequeo'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='empleado',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Empleado'),
        ),
        migrations.AlterField(
            model_name='inmunizacion',
            name='fecha_aplicacion',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 2, 11, 40, 104343, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inmunizacion',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='empleado',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Empleado'),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 2, 11, 40, 91309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 2, 11, 40, 91309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revisionaparatosistema',
            name='aparato_sistema',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.AparatoSistema'),
        ),
        migrations.AlterField(
            model_name='revisionaparatosistema',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.FichaMedica'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='inmunizacion',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='historial.Inmunizacion'),
        ),
    ]
