# Generated by Django 2.0.6 on 2018-07-15 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0012_auto_20180711_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='examen_fisico',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 15, 30, 16, 668774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 15, 30, 16, 670810, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='columna',
            name='detalle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 15, 30, 16, 667772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 15, 30, 16, 667772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 15, 30, 16, 667772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='extremidades',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inmunizacion',
            name='fecha_aplicacion',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 15, 30, 16, 673817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 15, 30, 16, 669775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 15, 30, 16, 669775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='regional',
            name='abdomen',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='regional',
            name='cabeza_cuello',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='regional',
            name='corazon',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='regional',
            name='piel_tegumentos',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='regional',
            name='pulmones',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='regional',
            name='torax',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='regionlumbar',
            name='detalle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='somaticogeneral',
            name='actividades_psicomotoras',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='somaticogeneral',
            name='apariencia',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='somaticogeneral',
            name='estado_nutricional',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
