# Generated by Django 2.0.6 on 2018-07-16 04:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0017_auto_20180715_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 16, 4, 11, 25, 523328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='motivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='plan_cuidados',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 16, 4, 11, 25, 537366, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 16, 4, 11, 25, 521322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2018, 7, 16, 4, 11, 25, 518314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 16, 4, 11, 25, 518314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inmunizacion',
            name='fecha_aplicacion',
            field=models.DateField(default=datetime.datetime(2018, 7, 16, 4, 11, 25, 556414, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 7, 16, 4, 11, 25, 533355, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 7, 16, 4, 11, 25, 533355, tzinfo=utc)),
        ),
    ]
