# Generated by Django 2.0 on 2018-07-21 05:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_inicio', models.IntegerField()),
                ('actividad', models.CharField(max_length=300)),
                ('riesgos', models.CharField(max_length=300)),
                ('epps', models.CharField(max_length=300)),
                ('tiempo', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentePatologicoFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentePatologicoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_patologia', models.CharField(max_length=100)),
                ('detalle_patologia', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AparatoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hallazgo', models.CharField(max_length=300)),
                ('detalle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AtencionEnfermeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2018, 7, 21, 5, 5, 30, 464986, tzinfo=utc))),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('diagnostico', models.CharField(blank=True, max_length=300)),
                ('plan_cuidados', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Chequeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2018, 7, 21, 5, 5, 30, 468549, tzinfo=utc))),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cifosis_acentuada', models.BooleanField()),
                ('contractura_muscular', models.BooleanField()),
                ('dolor', models.BooleanField()),
                ('lordosis_acentuada', models.BooleanField()),
                ('escoliosis', models.BooleanField()),
                ('motricidad', models.BooleanField()),
                ('lassegue', models.BooleanField()),
                ('detalle', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime(2018, 7, 21, 5, 5, 30, 464074, tzinfo=utc))),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('problema_actual', models.CharField(blank=True, max_length=300)),
                ('revision', models.CharField(blank=True, max_length=300)),
                ('prescripcion', models.CharField(blank=True, max_length=300)),
                ('examen_fisico', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('consulta_medica', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ConsultaMedica')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=9)),
                ('lugar_nacimiento', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime(2018, 7, 21, 5, 5, 30, 462866, tzinfo=utc))),
                ('ocupacion_actual', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(default=datetime.datetime(2018, 7, 21, 5, 5, 30, 462942, tzinfo=utc))),
                ('foto', models.IntegerField()),
                ('nombre_usuario', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('factores_riesgo', models.CharField(max_length=300)),
                ('antecedente_laboral', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AntecedenteLaboral')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.FloatField()),
                ('peso', models.FloatField()),
                ('indice_masa_corporal', models.FloatField()),
                ('columna', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Columna')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenLaboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('archivo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Extremidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phalen', models.BooleanField()),
                ('tinel', models.BooleanField()),
                ('dolor', models.BooleanField()),
                ('signo_cajon_rodilla', models.BooleanField()),
                ('finkelstein', models.BooleanField()),
                ('motricidad', models.BooleanField()),
                ('observaciones', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('chequeo', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Chequeo')),
                ('empleado', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Inmunizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=500)),
                ('fecha_aplicacion', models.DateField(default=datetime.datetime(2018, 7, 21, 5, 5, 30, 474700, tzinfo=utc))),
                ('ficha_medica', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.datetime(2018, 7, 21, 5, 5, 30, 467660, tzinfo=utc))),
                ('fecha_fin', models.DateField(default=datetime.datetime(2018, 7, 21, 5, 5, 30, 467696, tzinfo=utc))),
                ('dias', models.IntegerField()),
                ('diagnostico', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Diagnostico')),
                ('empleado', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piel_tegumentos', models.CharField(blank=True, max_length=300)),
                ('cabeza_cuello', models.CharField(blank=True, max_length=300)),
                ('torax', models.CharField(blank=True, max_length=300)),
                ('corazon', models.CharField(blank=True, max_length=300)),
                ('pulmones', models.CharField(blank=True, max_length=300)),
                ('abdomen', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RegionLumbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolor_punio_percusion', models.BooleanField()),
                ('motricidad', models.BooleanField()),
                ('detalle', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionAparatoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparato_sistema', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AparatoSistema')),
                ('ficha_medica', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_sistolica', models.IntegerField()),
                ('presion_distolica', models.IntegerField()),
                ('pulso', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('atencion_enfermeria', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AtencionEnfermeria')),
                ('consulta_medica', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ConsultaMedica')),
            ],
        ),
        migrations.CreateModel(
            name='SomaticoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apariencia', models.CharField(blank=True, max_length=300)),
                ('estado_nutricional', models.CharField(blank=True, max_length=300)),
                ('actividades_psicomotoras', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=5)),
                ('inmunizacion', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Inmunizacion')),
            ],
        ),
        migrations.AddField(
            model_name='examenlaboratorio',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='extremidades',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Extremidades'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='region_lumbar',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RegionLumbar'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='regional',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Regional'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='signos_vitales',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SignosVitales'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='somatico_general',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SomaticoGeneral'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='enfermedad',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Enfermedad'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='empleado',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Empleado'),
        ),
        migrations.AddField(
            model_name='atencionenfermeria',
            name='empleado',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Empleado'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicopersonal',
            name='consulta_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ConsultaMedica'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicopersonal',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicofamiliar',
            name='consulta_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ConsultaMedica'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicofamiliar',
            name='enfermedad',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Enfermedad'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicofamiliar',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica'),
        ),
        migrations.AddField(
            model_name='antecedentelaboral',
            name='ficha_medica',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica'),
        ),
    ]
