# Generated by Django 2.0 on 2018-07-30 22:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(max_length=50)),
                ('edad_inicio', models.CharField(max_length=2)),
                ('actual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentePatologicoFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=100)),
                ('patologia', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentePatologicoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AparatoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AtencionEnfermeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivoAtencion', models.CharField(blank=True, max_length=300)),
                ('planCuidados', models.CharField(blank=True, max_length=500)),
                ('fechaAtencion', models.DateField(default=datetime.datetime(2018, 7, 30, 22, 40, 12, 337519, tzinfo=utc))),
                ('diagnosticoEnfermeria', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cifosis_acentuada', models.BooleanField()),
                ('contractura_muscular', models.BooleanField()),
                ('dolor', models.BooleanField()),
                ('lordosis_acentuada', models.BooleanField()),
                ('escoliosis', models.BooleanField()),
                ('motricidad', models.CharField(blank=True, max_length=300)),
                ('lassegue', models.CharField(blank=True, max_length=300)),
                ('detalle_alteracion', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen_fisico', models.CharField(max_length=300)),
                ('fechaConsulta', models.DateField(default=datetime.datetime(2018, 7, 30, 22, 40, 12, 336241, tzinfo=utc))),
                ('prescripcion', models.CharField(blank=True, max_length=300)),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('prob_actual', models.CharField(blank=True, max_length=300)),
                ('revision_medica', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEnfermedad', models.CharField(max_length=100)),
                ('consulta_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ConsultaMedica')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('cedula', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=15)),
                ('estadoCivil', models.CharField(max_length=20)),
                ('lugarNacimiento', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=30)),
                ('instruccion', models.CharField(max_length=30)),
                ('profesion', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2018, 7, 30, 22, 40, 12, 334780, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('actividad', models.CharField(max_length=100)),
                ('epps', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.FloatField()),
                ('peso', models.FloatField()),
                ('indice_masa_corporal', models.FloatField()),
                ('columna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Columna')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenLaboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
                ('consulta_medica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ConsultaMedica')),
            ],
        ),
        migrations.CreateModel(
            name='Extremidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolor', models.CharField(blank=True, max_length=20)),
                ('phalen', models.CharField(blank=True, max_length=20)),
                ('tinel', models.CharField(blank=True, max_length=20)),
                ('signo_cajon_rodilla', models.CharField(blank=True, max_length=20)),
                ('finkelstein', models.CharField(blank=True, max_length=20)),
                ('motricidad', models.CharField(blank=True, max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FactorRiesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ciudad', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=15)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Inmunizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(blank=True, max_length=20)),
                ('columna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Columna')),
                ('extremidades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Extremidades')),
            ],
        ),
        migrations.CreateModel(
            name='Lumbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolor_punio_percusion', models.BooleanField()),
                ('motricidad', models.BooleanField()),
                ('detalle_alteracion', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(default=datetime.datetime(2018, 7, 30, 22, 40, 12, 342153, tzinfo=utc))),
                ('fecha_fin', models.DateField(default=datetime.datetime(2018, 7, 30, 22, 40, 12, 342211, tzinfo=utc))),
                ('dias_permiso', models.IntegerField()),
                ('observaciones_permiso', models.CharField(max_length=100)),
                ('consulta_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ConsultaMedica')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Diagnostico')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piel_tegumentos', models.CharField(blank=True, max_length=300)),
                ('cabeza_cuello', models.CharField(blank=True, max_length=300)),
                ('torax', models.CharField(blank=True, max_length=300)),
                ('corazon', models.CharField(blank=True, max_length=300)),
                ('pulmones', models.CharField(blank=True, max_length=300)),
                ('abdomen', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2018, 7, 30, 22, 40, 12, 338711, tzinfo=utc))),
                ('presion_sistolica', models.IntegerField()),
                ('presion_distolica', models.IntegerField()),
                ('pulso', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('atencion_enfermeria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AtencionEnfermeria')),
                ('consulta_medica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ConsultaMedica')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SomaticoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apariencia', models.CharField(blank=True, max_length=300)),
                ('estado_nutricional', models.CharField(blank=True, max_length=300)),
                ('actividades_psicomotoras', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dosis', models.IntegerField()),
                ('fecha', models.DateField(default=datetime.datetime(2018, 7, 30, 22, 40, 12, 344240, tzinfo=utc))),
                ('inmunizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Inmunizacion')),
            ],
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='inmunizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Inmunizacion'),
        ),
        migrations.AddField(
            model_name='examenlaboratorio',
            name='ficha_medica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='extremidades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Extremidades'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='ficha_medica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='lumbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Lumbar'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='regional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Regional'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='signos_vitales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SignosVitales'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='somatico_general',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SomaticoGeneral'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='enfermedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Enfermedad'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Empleado'),
        ),
        migrations.AddField(
            model_name='atencionenfermeria',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Empleado'),
        ),
        migrations.AddField(
            model_name='aparatosistema',
            name='ficha_medica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicopersonal',
            name='consulta_medica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ConsultaMedica'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicopersonal',
            name='ficha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicofamiliar',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica'),
        ),
        migrations.AddField(
            model_name='antecedentelaboral',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Empresa'),
        ),
        migrations.AddField(
            model_name='antecedentelaboral',
            name='ficha_medica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FichaMedica'),
        ),
    ]
