# Generated by Django 2.0 on 2018-08-04 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparatosistema',
            name='nombre',
            field=models.CharField(choices=[('Sistema nervioso', 'Sistema nervioso'), ('Órganos de los sentidos', 'Órganos de los sentidos'), ('Respiratorio', 'Respiratorio'), ('Digestivo', 'Digestivo'), ('Endócrino', 'Endócrino'), ('Músculo esquelético', 'Músculo esquelético'), ('Genital - urinario', 'Genital - urinario'), ('Piel y tegumentos', 'Piel y tegumentos'), ('Hemolinfático', 'Hemolinfático')], default='Digestivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fechaAtencion',
            field=models.DateField(default=datetime.datetime(2018, 8, 4, 18, 25, 28, 82700, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fechaConsulta',
            field=models.DateField(default=datetime.datetime(2018, 8, 4, 18, 25, 28, 81377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2018, 8, 4, 18, 25, 28, 79208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 8, 4, 18, 25, 28, 85774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 8, 4, 18, 25, 28, 85740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 4, 18, 25, 28, 83594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='dosis',
            field=models.CharField(choices=[('Primera', 'Primera'), ('Segunda', 'Segunda'), ('Tercera', 'Tercera'), ('Refuerzo', 'Refuerzo')], default='Primera', max_length=15),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 4, 18, 25, 28, 87236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(choices=[('Tétanos', 'Tétanos'), ('Hepatitis A - B', 'Hepatitis A - B'), ('Fiebre tifoidea', 'Fiebre tifoidea'), ('Fiebre amarilla', 'Fiebre amarilla')], default='Tétanos', max_length=30),
        ),
    ]
