# Generated by Django 2.0 on 2018-08-15 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180815_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisomedico',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='permiso_medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PermisoMedico'),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fechaAtencion',
            field=models.DateField(default=datetime.datetime(2018, 8, 15, 17, 2, 50, 894159, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fechaConsulta',
            field=models.DateField(default=datetime.datetime(2018, 8, 15, 17, 2, 50, 892725, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2018, 8, 15, 17, 2, 50, 889127, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 15, 17, 2, 50, 902937, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 8, 15, 17, 2, 50, 904540, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 8, 15, 17, 2, 50, 904489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 8, 15, 17, 2, 50, 904381, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 15, 17, 2, 50, 895315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 15, 17, 2, 50, 900578, tzinfo=utc)),
        ),
    ]
