# Generated by Django 2.0 on 2018-07-22 02:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180721_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='empleado',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Empleado'),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 2, 20, 14, 330857, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 2, 20, 14, 334318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 2, 20, 14, 330014, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 2, 20, 14, 329004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 2, 20, 14, 329070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inmunizacion',
            name='fecha_aplicacion',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 2, 20, 14, 339890, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 2, 20, 14, 333558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 7, 22, 2, 20, 14, 333524, tzinfo=utc)),
        ),
    ]
