# Generated by Django 2.0 on 2018-08-08 01:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180804_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RegionLumbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolor_punio_percusion', models.BooleanField()),
                ('motricidad', models.BooleanField()),
                ('detalle_alteracion', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='examenfisico',
            name='lumbar',
        ),
        migrations.RemoveField(
            model_name='examenlaboratorio',
            name='consulta_medica',
        ),
        migrations.RemoveField(
            model_name='examenlaboratorio',
            name='nombre',
        ),
        migrations.AddField(
            model_name='examenlaboratorio',
            name='tipo',
            field=models.CharField(choices=[('Laboratorio', 'Laboratorio'), ('Emo', 'Emo'), ('Coproparasitario', 'Coproparasitario'), ('Pruebas especiales de laboratorio', 'Pruebas especiales de laboratorio'), ('Oftalmología', 'Oftalmología'), ('Espirometría', 'Espirometría')], default='Laboratorio', max_length=50),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fechaAtencion',
            field=models.DateField(default=datetime.datetime(2018, 8, 8, 1, 43, 57, 330817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fechaConsulta',
            field=models.DateField(default=datetime.datetime(2018, 8, 8, 1, 43, 57, 329088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2018, 8, 8, 1, 43, 57, 324595, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 8, 8, 1, 43, 57, 336034, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 8, 8, 1, 43, 57, 335965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 8, 1, 43, 57, 332115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 8, 1, 43, 57, 338651, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Lumbar',
        ),
        migrations.AddField(
            model_name='examenconsulta',
            name='consulta_medica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ConsultaMedica'),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='region_lumbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RegionLumbar'),
        ),
    ]
