# Generated by Django 2.0 on 2018-08-10 23:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180808_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostico',
            old_name='tipoEnfermedad',
            new_name='tipo_enfermedad',
        ),
        migrations.RemoveField(
            model_name='permisomedico',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='permiso_medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PermisoMedico'),
        ),
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fechaAtencion',
            field=models.DateField(default=datetime.datetime(2018, 8, 10, 23, 34, 19, 601061, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fechaConsulta',
            field=models.DateField(default=datetime.datetime(2018, 8, 10, 23, 34, 19, 599723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2018, 8, 10, 23, 34, 19, 596903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 8, 10, 23, 34, 19, 604194, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 8, 10, 23, 34, 19, 604143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 10, 23, 34, 19, 602086, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 10, 23, 34, 19, 607217, tzinfo=utc)),
        ),
    ]
