# Generated by Django 2.1rc1 on 2018-08-01 00:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180731_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fechaAtencion',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 0, 57, 1, 805191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fechaConsulta',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 0, 57, 1, 805191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 0, 57, 1, 805191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='factorriesgo',
            name='nombre',
            field=models.CharField(choices=[('Físico', (('Ruido', 'Ruido'), ('Vibración', 'Vibración'), ('Iluminación', 'Iluminación'), ('Radiaciones ionizantes', 'Radiaciones ionizantes'), ('Radiaciones no ionizantes', 'Radiaciones no ionizantes'), ('Presión', 'Presión'), ('Contacto con circuitos eléctricos', 'Contacto con circuitos eléctricos'))), ('Químico', (('Vapores', 'Vapores'), ('Gases (crudo, lixiviados, otros)', '(crudo, lixiviados, otros)'), ('Fibras (de madera, aluminio, otros)', 'Fibras (de madera, aluminio, otros)'), ('Polvos orgánicos', 'Polvos orgánicos'), ('Polvos inorgánicos', 'Polvos inorgánicos'), ('Humos metálicos (soldadura, otros)', 'Humos metálicos (soldadura, otros)'), ('Humos de combustión', 'Humos de combustión'), ('Neblinas', 'Neblinas'), ('Líquidos', 'Líquidos')))], max_length=50),
        ),
        migrations.AlterField(
            model_name='factorriesgo',
            name='tipo',
            field=models.CharField(choices=[('Físico', 'Físico'), ('Químico', 'Químico')], max_length=50),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 0, 57, 1, 805191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 0, 57, 1, 805191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 0, 57, 1, 805191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 0, 57, 1, 805191, tzinfo=utc)),
        ),
    ]
