# Generated by Django 2.0 on 2018-08-01 01:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180801_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fechaAtencion',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 35, 44, 760958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='examen_fisico',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fechaConsulta',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 35, 44, 759939, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 35, 44, 758023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='consulta_medica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ConsultaMedica'),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='doctor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 35, 44, 764059, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 35, 44, 764024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='observaciones_permiso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 35, 44, 761900, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 35, 44, 765458, tzinfo=utc)),
        ),
    ]
