# Generated by Django 2.1rc1 on 2018-08-01 01:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180731_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fechaAtencion',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 37, 17, 233260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fechaConsulta',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 37, 17, 233260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 37, 17, 233260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='factorriesgo',
            name='nombre',
            field=models.CharField(choices=[('Físico', (('Ruido', 'Ruido'), ('Vibración', 'Vibración'), ('Iluminación', 'Iluminación'), ('Radiaciones ionizantes', 'Radiaciones ionizantes'), ('Radiaciones no ionizantes', 'Radiaciones no ionizantes'), ('Presión', 'Presión'), ('Contacto con circuitos eléctricos', 'Contacto con circuitos eléctricos'))), ('Químico', (('Vapores', 'Vapores'), ('Gases (crudo, lixiviados, otros)', '(crudo, lixiviados, otros)'), ('Fibras (de madera, aluminio, otros)', 'Fibras (de madera, aluminio, otros)'), ('Polvos orgánicos', 'Polvos orgánicos'), ('Polvos inorgánicos', 'Polvos inorgánicos'), ('Humos metálicos (soldadura, otros)', 'Humos metálicos (soldadura, otros)'), ('Humos de combustión', 'Humos de combustión'), ('Neblinas', 'Neblinas'), ('Líquidos', 'Líquidos'))), ('Biológico', (('Bacterias, hongos, virus, etc', 'Bacterias, hongos, virus, etc'), ('Insalubridad en áreas', 'Insalubridad en áreas'))), ('Ergonómicos', (('Cargas', 'Cargas'), ('Uso de pantallas de visualización', 'Uso de pantallas de visualización'), ('Posturas en el trabajo mantenidas', 'Posturas en el trabajo mantenidas'), ('Fatiga por esfuerzo físico', 'Fatiga por esfuerzo físico'), ('Movimientos repetitivos', 'Movimientos repetitivos'))), ('Mecánicos', (('Contactos con superficies calientes', 'Contactos con superficies calientes'), ('Contacto con herramientas, utensilios cortopunzantes', 'Contacto con herramientas, utensilios cortopunzantes'), ('Golpes con objetos, herramientas', 'Golpes con objetos, herramientas'), ('Atrapamiento en partes', 'Atrapamiento en partes'), ('Caída de objetos', 'Caída de objetos'), ('Derrumbes', 'Derrumbes'), ('Transporte en vehículos - colisión', 'Transporte en vehículos - colisión'))), ('Psicosociales', (('Medio ambiente físico de trabajo', 'Medio ambiente físico de trabajo'), ('Factores propios de la tarea', 'Factores propios de la tarea'), ('Organización del tiempo de trabajo', 'Organización del tiempo de trabajo'), ('Gestión administrativa de la empresa', 'Gestión administrativa de la empresa')))], max_length=50),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 37, 17, 248883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 37, 17, 248883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 37, 17, 233260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 1, 1, 37, 17, 248883, tzinfo=utc)),
        ),
    ]
