# Generated by Django 2.0 on 2018-07-30 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180730_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionenfermeria',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 16, 17, 49, 354337, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chequeo',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 16, 17, 49, 357956, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 16, 17, 49, 353557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 16, 17, 49, 352473, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 16, 17, 49, 352539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inmunizacion',
            name='fecha_aplicacion',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 16, 17, 49, 363342, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 16, 17, 49, 357186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisomedico',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 16, 17, 49, 357152, tzinfo=utc)),
        ),
    ]
