from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(Empleado)
admin.site.register(ConsultaMedica)
admin.site.register(AtencionEnfermeria)
admin.site.register(SignosVitales)
admin.site.register(Enfermedad)
admin.site.register(Diagnostico)
admin.site.register(PermisoMedico)
admin.site.register(Inmunizacion)
admin.site.register(Vacuna)
admin.site.register(FichaMedica)
admin.site.register(AparatoSistema)
admin.site.register(AntecedentePatologicoPersonal)
admin.site.register(AntecedentePatologicoFamiliar)
admin.site.register(Empresa)
admin.site.register(AntecedenteLaboral)
admin.site.register(FactorRiesgo)
admin.site.register(ExamenLaboratorio)
admin.site.register(SomaticoGeneral)
admin.site.register(Regional)
admin.site.register(Columna)
admin.site.register(Lumbar)
admin.site.register(Extremidades)
admin.site.register(Localizacion)
admin.site.register(ExamenFisico)